In [ ]:
# TOPSIS Assignment - Part I
# Name: Avneet Sandhu
# Roll No: 102303289

import pandas as pd
import numpy as np

print("Notebook start successfull")


Notebook start successfull


In [ ]:
df = pd.read_csv("data.csv")
df

Fund Name    P1    P2   P3    P4     P5
0        M1  0.88  0.77  3.3  49.9  13.71
1        M2  0.61  0.37  4.1  63.8  17.22
2        M3  0.68  0.46  5.8  55.7  15.66
3        M4  0.65  0.42  3.5  34.7   9.82
4        M5  0.93  0.86  5.0  55.3  15.52
5        M6  0.91  0.83  3.2  50.6  13.89
6        M7  0.91  0.83  4.6  64.3  17.66
7        M8  0.92  0.85  5.3  36.5  10.89

Step : Convert categorical to numeric(Already numeric in our dataset)

Why we do this:

1.First column is just names

2.TOPSIS math works only on numbers

In [ ]:
alternatives = df.iloc[:, 0]     # Mobile names
X = df.iloc[:, 1:]               # Criteria values (P1,P2,P3,P4,P5)

X


P1    P2   P3    P4     P5
0  0.88  0.77  3.3  49.9  13.71
1  0.61  0.37  4.1  63.8  17.22
2  0.68  0.46  5.8  55.7  15.66
3  0.65  0.42  3.5  34.7   9.82
4  0.93  0.86  5.0  55.3  15.52
5  0.91  0.83  3.2  50.6  13.89
6  0.91  0.83  4.6  64.3  17.66
7  0.92  0.85  5.3  36.5  10.89

Step 2.1: Vector Normalization

Calculate Root of Sum of Squares

In [ ]:
X = df.iloc[:, 1:]   # criteria values
root_sum_squares = np.sqrt((X ** 2).sum())

root_sum_squares


P1      2.323553
P2      1.989397
P3     12.572987
P4    148.162816
P5     41.114848
dtype: float64

Step 2.2: Vector Normalization

Normalized Decision Matrix

In [ ]:
normalized_decision_matrix = X / root_sum_squares
normalized_decision_matrix

P1        P2        P3        P4        P5
0  0.378730  0.387052  0.262467  0.336792  0.333456
1  0.262529  0.185986  0.326096  0.430607  0.418827
2  0.292655  0.231226  0.461306  0.375938  0.380884
3  0.279744  0.211119  0.278375  0.234202  0.238843
4  0.400249  0.432292  0.397678  0.373238  0.377479
5  0.391642  0.417212  0.254514  0.341516  0.337834
6  0.391642  0.417212  0.365864  0.433982  0.429529
7  0.395945  0.427265  0.421539  0.246351  0.264868

Step 3.1: Weight Assignment

In [ ]:
weights = np.array([0.20, 0.20, 0.20, 0.20, 0.20])
weights

array([0.2, 0.2, 0.2, 0.2, 0.2])

Step 3.2: Weight Assignment

Weighted Normalized Decision Matrix

In [ ]:
weighted_normalized_decision_matrix = normalized_decision_matrix * weights
weighted_normalized_decision_matrix

P1        P2        P3        P4        P5
0  0.075746  0.077410  0.052493  0.067358  0.066691
1  0.052506  0.037197  0.065219  0.086121  0.083765
2  0.058531  0.046245  0.092261  0.075188  0.076177
3  0.055949  0.042224  0.055675  0.046840  0.047769
4  0.080050  0.086458  0.079536  0.074648  0.075496
5  0.078328  0.083442  0.050903  0.068303  0.067567
6  0.078328  0.083442  0.073173  0.086796  0.085906
7  0.079189  0.085453  0.084308  0.049270  0.052974

Step 4: Find Ideal Best and Ideal Worst

In [ ]:
impacts = ["-", "+", "+", "+","-"]

ideal_best = []
ideal_worst = []

for i in range(len(impacts)):
    if impacts[i] == "+":
        ideal_best.append(weighted_normalized_decision_matrix.iloc[:, i].max())
        ideal_worst.append(weighted_normalized_decision_matrix.iloc[:, i].min())
    else:
        ideal_best.append(weighted_normalized_decision_matrix.iloc[:, i].min())
        ideal_worst.append(weighted_normalized_decision_matrix.iloc[:, i].max())

ideal_best = np.array(ideal_best)
ideal_worst = np.array(ideal_worst)

ideal_best, ideal_worst


(array([0.05250579, 0.08645836, 0.09226129, 0.08679641, 0.04776863]),
 array([0.08004981, 0.0371972 , 0.05090278, 0.04684036, 0.08590571]))

Step 5: Calculate Euclidean Distance

In [ ]:
S_plus = np.sqrt(((weighted_normalized_decision_matrix - ideal_best) ** 2).sum(axis=1))
S_minus = np.sqrt(((weighted_normalized_decision_matrix - ideal_worst) ** 2).sum(axis=1))

S_plus, S_minus


(0    0.054216
 1    0.066739
 2    0.050943
 3    0.070026
 4    0.042860
 5    0.055860
 6    0.049947
 7    0.047027
 dtype: float64,
 0    0.049278
 1    0.050112
 2    0.056157
 3    0.045644
 4    0.064250
 5    0.054208
 6    0.065069
 7    0.067348
 dtype: float64)

Step 6: Calculate Performance Score

In [ ]:
performance_score = S_minus / (S_plus + S_minus)
performance_score


0    0.476145
1    0.428852
2    0.524343
3    0.394604
4    0.599850
5    0.492495
6    0.565740
7    0.588831
dtype: float64

Step 7: TOPSIS Score and Rank

In [ ]:
final_result = pd.DataFrame({
    "Mobile": df.iloc[:, 0],
    "Performance Score (Pi)": performance_score,
    "Rank": performance_score.rank(ascending=False).astype(int)
})

final_result.sort_values("Rank")


Mobile  Performance Score (Pi)  Rank
4     M5                0.599850     1
7     M8                0.588831     2
6     M7                0.565740     3
2     M3                0.524343     4
5     M6                0.492495     5
0     M1                0.476145     6
1     M2                0.428852     7
3     M4                0.394604     8

In [ ]:
python topsis.py data.csv 0.2,0.2,0.2,0.2,0.2 -,+,+,+,+ output.csv


Result saved successfully in output.csv
